-- =====================================================
-- Remove unused p_lang parameter from rpc_get_pois_facets
-- =====================================================
--
-- The p_lang parameter was never used in the function logic.
-- All labels are generated statically without language support.
--
-- INSTRUCTIONS:
-- 1. Open your Supabase SQL Editor
-- 2. Find the rpc_get_pois_facets function definition
-- 3. Apply the following changes:
--
-- CHANGE 1: Remove p_lang from function signature
-- ------------------------------------------------
-- BEFORE:
--   CREATE OR REPLACE FUNCTION rpc_get_pois_facets(
--     p_city_slug text,
--     p_primary_types text[],
--     ...other params...,
--     p_lang text DEFAULT 'fr'  -- <-- REMOVE THIS LINE
--   )
--
-- AFTER:
--   CREATE OR REPLACE FUNCTION rpc_get_pois_facets(
--     p_city_slug text,
--     p_primary_types text[],
--     ...other params...
--     -- p_lang removed
--   )
--
--
-- CHANGE 2: Remove lang normalization from norm CTE
-- -------------------------------------------------
-- BEFORE:
--   norm AS (
--     SELECT
--       lower(p_city_slug) AS city_slug,
--       ...
--       CASE WHEN p_lang IN ('fr','en') THEN p_lang ELSE 'fr' END AS lang  -- <-- REMOVE THIS LINE
--   ),
--
-- AFTER:
--   norm AS (
--     SELECT
--       lower(p_city_slug) AS city_slug,
--       ...
--       -- lang removed (was never used)
--   ),
--
-- That's it! The function will work exactly the same way since p_lang
-- was never referenced anywhere in the function logic.
