# fly.toml app configuration file generated for gatto-api
app = "gatto-api"
primary_region = "cdg"

[build]

[env]
  NODE_ENV = "production"
  HOST = "0.0.0.0"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1